### ISSUE TITLE
AttributeError: module 'numpy' has no attribute 'extend' when running 2D image 

### ISSUE THREAD

**Issue by chili-chiu** [alexisjapas/napari-vesicles-segmentation#1]
(1) Open a 2D image (for example, File > Open Sample > napari > cell)
(2) Open the plugin
(3) Click "run segmentation"
(4)AttributeError: module 'numpy' has no attribute 'extend'

This error does not occur when working with 3D images.

**Comment by alexisjapas** [comment]
Hi, thank you for your reporting, this is now fixed using expand_dims numpy function instead of extend.
